# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-07 16:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mycalendarapp', '0002_auto_20160607_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='time_end',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Koniec'),
        ),
    ]
